"use client"

import Head from 'next/head'
import React, { useEffect } from 'react'
import ClientLayout from '../../layout/client/ClientLayout'
import RestaurantItem from '../../components/client/RestaurantItem'
import useRestaurantStore from '../../store/restaurantStore'

const Restaurant = () => {
    const { restaurant, setRestaurant } = useRestaurantStore(state => {
        return state
    });
    useEffect(() => {
        setRestaurant(null)
    }, [])
    return (
        <div>
            <Head>
                <title>Restaurants</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <ClientLayout>
                <RestaurantItem />
            </ClientLayout>
        </div>
    )
}

export default Restaurant