import Head from 'next/head'
import React from 'react'
import ClientLayout from '../../layout/client/ClientLayout'
import RestaurantItem from '../../components/client/RestaurantItem'

const Restaurant = () => {
    return (
        <div>
            <Head>
                <title>Restaurants</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <ClientLayout>
                <RestaurantItem />
            </ClientLayout>
        </div>
    )
}

export default Restaurant